// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHVFCV09i-gf0crIju71MXFRw39D0cB7Y',
    appId: '1:987191499787:web:0be8e4281774dad57fbb0e',
    messagingSenderId: '987191499787',
    projectId: 'instagramclone-66e02',
    authDomain: 'instagramclone-66e02.firebaseapp.com',
    storageBucket: 'instagramclone-66e02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs84HCi_NYk1Js_Vf0Ayla1aeLQwkZ5dM',
    appId: '1:987191499787:android:2d97d133b0ae52947fbb0e',
    messagingSenderId: '987191499787',
    projectId: 'instagramclone-66e02',
    storageBucket: 'instagramclone-66e02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXJqU2mMv52XBJpb0wI-Kx9JF6w6OwwmY',
    appId: '1:987191499787:ios:1e91ed4ce422f4c47fbb0e',
    messagingSenderId: '987191499787',
    projectId: 'instagramclone-66e02',
    storageBucket: 'instagramclone-66e02.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
